const { contextBridge, ipcRenderer, shell } = require('electron');

contextBridge.exposeInMainWorld('api', {
  openExternal: (url) => ipcRenderer.send('open-external', url),
  onSpots: (cb) => ipcRenderer.on('spots', (_e, data) => cb(data)),
  onSpotsError: (cb) => ipcRenderer.on('spots-error', (_e, msg) => cb(msg)),
  onCatStatus: (cb) => ipcRenderer.on('cat-status', (_e, s) => cb(s)),
  tune: (frequency, mode, bearing) => ipcRenderer.send('tune', { frequency, mode, bearing }),
  refresh: () => ipcRenderer.send('refresh'),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  saveSettings: (s) => ipcRenderer.invoke('save-settings', s),
  listPorts: () => ipcRenderer.invoke('list-ports'),
  listRigs: () => ipcRenderer.invoke('list-rigs'),
  testHamlib: (config) => ipcRenderer.invoke('test-hamlib', config),
  testSerialCat: (config) => ipcRenderer.invoke('test-serial-cat', config),
  connectCat: (target) => ipcRenderer.send('connect-cat', target),
  onCatFrequency: (cb) => ipcRenderer.on('cat-frequency', (_e, hz) => cb(hz)),
  chooseAdifFile: () => ipcRenderer.invoke('choose-adif-file'),
  importAdif: () => ipcRenderer.invoke('import-adif'),
  parseAdif: () => ipcRenderer.invoke('parse-adif'),
  onDxccData: (cb) => ipcRenderer.on('dxcc-data', (_e, data) => cb(data)),
  onClusterStatus: (cb) => ipcRenderer.on('cluster-status', (_e, s) => cb(s)),
  onRbnSpots: (cb) => ipcRenderer.on('rbn-spots', (_e, data) => cb(data)),
  onRbnStatus: (cb) => ipcRenderer.on('rbn-status', (_e, s) => cb(s)),
  clearRbn: () => ipcRenderer.send('rbn-clear'),
  onSolarData: (cb) => ipcRenderer.on('solar-data', (_e, d) => cb(d)),
  onUpdateAvailable: (cb) => ipcRenderer.on('update-available', (_e, d) => cb(d)),
  onCatLog: (cb) => ipcRenderer.on('cat-log', (_e, msg) => cb(msg)),
  onWorkedCallsigns: (cb) => ipcRenderer.on('worked-callsigns', (_e, data) => cb(data)),
  onWorkedParks: (cb) => ipcRenderer.on('worked-parks', (_e, data) => cb(data)),
  choosePotaParksFile: () => ipcRenderer.invoke('choose-pota-parks-file'),
  onWsjtxStatus: (cb) => ipcRenderer.on('wsjtx-status', (_e, s) => cb(s)),
  onWsjtxState: (cb) => ipcRenderer.on('wsjtx-state', (_e, s) => cb(s)),
  onWsjtxDecode: (cb) => ipcRenderer.on('wsjtx-decode', (_e, d) => cb(d)),
  onWsjtxClear: (cb) => ipcRenderer.on('wsjtx-clear', () => cb()),
  onWsjtxQsoLogged: (cb) => ipcRenderer.on('wsjtx-qso-logged', (_e, q) => cb(q)),
  wsjtxReply: (decode) => ipcRenderer.send('wsjtx-reply', decode),
  wsjtxHaltTx: () => ipcRenderer.send('wsjtx-halt-tx'),
  saveQso: (qsoData) => ipcRenderer.invoke('save-qso', qsoData),
  getRecentQsos: () => ipcRenderer.invoke('get-recent-qsos'),
  getDefaultLogPath: () => ipcRenderer.invoke('get-default-log-path'),
  chooseLogFile: (currentPath) => ipcRenderer.invoke('choose-log-file', currentPath),
  onQrzData: (cb) => ipcRenderer.on('qrz-data', (_e, data) => cb(data)),
  onDonorCallsigns: (cb) => ipcRenderer.on('donor-callsigns', (_e, data) => cb(data)),
  minimize: () => ipcRenderer.send('win-minimize'),
  maximize: () => ipcRenderer.send('win-maximize'),
  close: () => ipcRenderer.send('win-close'),
});
