const { contextBridge, ipcRenderer, shell } = require('electron');

contextBridge.exposeInMainWorld('api', {
  openExternal: (url) => ipcRenderer.send('open-external', url),
  onSpots: (cb) => ipcRenderer.on('spots', (_e, data) => cb(data)),
  onSpotsError: (cb) => ipcRenderer.on('spots-error', (_e, msg) => cb(msg)),
  onCatStatus: (cb) => ipcRenderer.on('cat-status', (_e, s) => cb(s)),
  tune: (frequency, mode) => ipcRenderer.send('tune', { frequency, mode }),
  refresh: () => ipcRenderer.send('refresh'),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  saveSettings: (s) => ipcRenderer.invoke('save-settings', s),
  listPorts: () => ipcRenderer.invoke('list-ports'),
  listRigs: () => ipcRenderer.invoke('list-rigs'),
  testHamlib: (config) => ipcRenderer.invoke('test-hamlib', config),
  connectCat: (target) => ipcRenderer.send('connect-cat', target),
  onCatFrequency: (cb) => ipcRenderer.on('cat-frequency', (_e, hz) => cb(hz)),
  chooseAdifFile: () => ipcRenderer.invoke('choose-adif-file'),
  parseAdif: () => ipcRenderer.invoke('parse-adif'),
  onDxccData: (cb) => ipcRenderer.on('dxcc-data', (_e, data) => cb(data)),
  onClusterStatus: (cb) => ipcRenderer.on('cluster-status', (_e, s) => cb(s)),
  onRbnSpots: (cb) => ipcRenderer.on('rbn-spots', (_e, data) => cb(data)),
  onRbnStatus: (cb) => ipcRenderer.on('rbn-status', (_e, s) => cb(s)),
  clearRbn: () => ipcRenderer.send('rbn-clear'),
  onSolarData: (cb) => ipcRenderer.on('solar-data', (_e, d) => cb(d)),
  onUpdateAvailable: (cb) => ipcRenderer.on('update-available', (_e, d) => cb(d)),
  saveQso: (qsoData) => ipcRenderer.invoke('save-qso', qsoData),
  getDefaultLogPath: () => ipcRenderer.invoke('get-default-log-path'),
  chooseLogFile: (currentPath) => ipcRenderer.invoke('choose-log-file', currentPath),
  minimize: () => ipcRenderer.send('win-minimize'),
  maximize: () => ipcRenderer.send('win-maximize'),
  close: () => ipcRenderer.send('win-close'),
});
