// Regenerates cty-data.js from AD1C's cty.csv (country-files.com), which —
// unlike cty.dat — carries the ADIF DXCC entity number.
//
//   node build-cty.mjs path/to/cty.csv
//
// Rows starting with "*" are CQ WAE-only entities (not DXCC); they are
// skipped so their prefixes resolve to the parent DXCC entity.
import fs from 'fs';

const src = process.argv[2];
if (!src) { console.error('usage: node build-cty.mjs cty.csv'); process.exit(1); }
const entities = [];
const prefixes = {};
const calls = {};
for (const line of fs.readFileSync(src, 'utf8').split(/\r?\n/)) {
  if (!line.trim() || line.startsWith('*')) continue;
  const f = line.split(',');
  const name = f[1];
  const dxcc = parseInt(f[2], 10);
  const cont = f[3];
  if (!Number.isFinite(dxcc)) continue;
  const idx = entities.push([name, dxcc, cont]) - 1;
  for (let tok of f.slice(9).join(',').replace(/;\s*$/, '').split(/\s+/)) {
    tok = tok.replace(/\(.*?\)|\[.*?\]|<.*?>|\{.*?\}|~.*?~/g, '').trim();
    if (!tok || tok === '=VERSION') continue;
    if (tok.startsWith('=')) calls[tok.slice(1)] = idx;
    else prefixes[tok] = idx;
  }
}
const out = `// GENERATED by build-cty.mjs from cty.csv (${new Date().toISOString().slice(0, 10)}). Do not edit.
// ENTITIES[i] = [name, dxcc, continent]; PREFIXES / CALLS map to an index.
export const ENTITIES = ${JSON.stringify(entities)};
export const PREFIXES = ${JSON.stringify(prefixes)};
export const CALLS = ${JSON.stringify(calls)};
`;
fs.writeFileSync(new URL('./cty-data.js', import.meta.url), out);
console.log(`${entities.length} entities, ${Object.keys(prefixes).length} prefixes, ${Object.keys(calls).length} exact calls, ${out.length} bytes`);
