name = "potacat-sstv-packs"
main = "index.js"
compatibility_date = "2024-01-01"
account_id = "3dc9c47e0ae659e8eeed97bc7f6eeaf4"
workers_dev = true

routes = [
  { pattern = "packs.potacat.com", custom_domain = true }
]

# Create the KV namespace and paste its id here:
#   npx wrangler kv namespace create SSTV_PACKS
kv_namespaces = [
  { binding = "SSTV_PACKS", id = "fdc68c5765094814ad275f062ed97b9f" }
]
